### ISSUE TITLE
Support SCSS

### ISSUE THREAD

**Issue by JScriber** [JScriber/meal-poll#5]

**Comment by melvinlemoine** [comment]
Why not use SASS ? Is SCSS without {} and ; ! Cleaner code.

**Comment by JScriber** [comment]
In my opinion SASS is much harder to read than SCSS. I do admit it's cleaner code, but it's also a code that will be a hassle to maintain (for me at least).

That's why I keep on using SCSS in all my projects.

Also it's a bit off topic, but I no longer plan to add support for SCSS (nor SASS) as : 
- I don't have much CSS ;
- I've had enough struggle to eventually not get a webpack configuration that suits my needs (too much generated boilerplate, and I don't want to spend more time on it).
